In [3]:
##Importing the libraires and installing tensorflow for ANN

!pip install tensorflow

import numpy as np
import pandas as pd
import tensorflow as tf

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/93/21/9b035a4f823d6aee2917c75415be9a95861ff3d73a0a65e48edbf210cec1/tensorflow-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.15.0 from https://files.pythonhosted.org/packages/4c/48/1a5a15517f18eaa4ff8d598b1c000300b20c1bb0e624539d702117a0c369/tensorflow_intel-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
     ---------------------------------------- 0.0/57.5 kB ? eta -:--:--
     ---------------------------------------- 57.5

In [33]:
###Data Preprocessing 
###importing the dataset

dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
X[:,1]

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [34]:
##encoding categorical data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [35]:
###One hot encoding for geographical region
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [37]:
###train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [38]:
## feature Scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [40]:
###BUILDING ANN
###Initializing ANN
ann = tf.keras.models.Sequential()

###Adding the input layer and hidden laayer
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

###Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))

###Adding the output layer
ann.add(tf.keras.layers.Dense(units = 1,activation = 'sigmoid'))


In [41]:
###Training ANN
##Compiling the ANN
ann.compile(optimizer = 'adam', loss= 'binary_crossentropy',metrics = ['accuracy'])

In [42]:
##Trainingthe ANN on training set
ann.fit(X_train,y_train,batch_size = 32,epochs =100)

Epoch 1/100


250/250 [==============================] - 3s 3ms/step - loss: 0.5239 - accuracy: 0.7940
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4586 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4403 - accuracy: 0.7975
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4308 - accuracy: 0.7983
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4230 - accuracy: 0.7991
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4146 - accuracy: 0.7999
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4069 - accuracy: 0.8009
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3994 - accuracy: 0.8273
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3921 - accuracy: 0.8353
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3838 - accu

Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 0.8604
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3330 - accuracy: 0.8626
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3328 - accuracy: 0.8620
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3326 - accuracy: 0.8634
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3327 - accuracy: 0.8605
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3328 - accuracy: 0.8629
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3327 - accuracy: 0.8630
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3324 - accuracy: 0.8622
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3328 - accuracy: 0.8629
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3326

In [45]:
##Making the predictions and evaluating the model
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [46]:
##Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1534   61]
 [ 210  195]]


0.8645